name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- run: ls
      #- run: rm -f .npmrc
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #- run: docker build -t vite/host:clean . --build-arg NPM_TOKEN=${{ secrets.NODE_AUTH_TOKEN }}
      - uses: docker/build-push-action@v5.3.0
        with:
          tags: deuspaul/calculator:latest
          push: true
          build-args: |
            NPM_TOKEN=${{ secrets.NODE_AUTH_TOKEN }}
      
    
