name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5.3.0
        with:
          tags: deuspaul/calculator:latest
          build-args: |
            --build-arg NPM_TOKEN=${{ secrets.PAT }}
      
    
